name = input("who are you?")
city = input('where do you live?')
hobby = input('what is your hobby?')
age = input('how old are you?')

print("YOUR DETAILS FILLED BY YOU")
print("Name:", name)
print("City:", city)
print("Hobby:", hobby)
print("Age:", age)